on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acryhz172.azurecr.io
        username: ${{ secrets.acr_acryhz172_username }}
        password: ${{ secrets.acr_acryhz172_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t acryhz172.azurecr.io/aksyhz172:${{ github.sha }}
        docker push acryhz172.azurecr.io/aksyhz172:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksyhz172_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aksyhz1728c2c | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aksyhz1728c2c`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aksyhz1728c2c
        container-registry-url: acryhz172.azurecr.io
        container-registry-username: ${{ secrets.acr_acryhz172_username }}
        container-registry-password: ${{ secrets.acr_acryhz172_password }}
        secret-name: aksyhz172dockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: aksyhz1728c2c
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          acryhz172.azurecr.io/aksyhz172:${{ github.sha }}
        imagepullsecrets: |
          aksyhz172dockerauth